---
# tasks file for timezone

- name: make sure tzdata is installed for Debian systems
  apt: pkg=tzdata state=present
  when: ansible_os_family=='Debian'
  tags: [timezone]

- name: make sure tzdata is installed for RHEL systems
  yum: pkg=tzdata state=present
  when: ansible_os_family=='RedHat'
  tags: [timezone]

- name: set timezone
  template: src=timezone.j2 dest=/etc/timezone
  tags: [timezone]

- name: set localtime
  copy:
    src: /usr/share/zoneinfo/{{ timezone }}
    dest: /etc/localtime
    owner: root
    group: root
    mode: 0644
  tags: [timezone]

- name: update the hardware clock
  command: dpkg-reconfigure -f noninteractive tzdata
  when: ansible_os_family=='Debian'
  tags: [timezone]
